### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by khanimdad** [JoaquimLey/bus-eta#1]
I tried to run this project but getting below error.

`2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
08-20 22:40:16.151 2300-2397/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
08-20 22:40:16.152 2300-2397/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
08-20 22:40:21.171 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 249, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
08-20 22:40:21.171 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
08-20 22:40:21.171 2300-2397/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
08-20 22:40:21.172 2300-2397/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
08-20 22:40:26.191 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 257, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
08-20 22:40:26.191 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
08-20 22:40:26.191 2300-2397/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
08-20 22:40:26.192 2300-2397/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
08-20 22:40:31.211 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 265, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
08-20 22:40:31.213 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
08-20 22:40:31.213 2300-2397/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
08-20 22:40:31.214 2300-2397/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
08-20 22:40:33.465 3214-3214/? E/cutils-trace: Error opening trace file: Permission denied (13)
08-20 22:40:33.503 3214-3214/? E/memtrack: Couldn't load memtrack module (No such file or directory)
08-20 22:40:33.503 3214-3214/? E/android.os.Debug: failed to load memtrack module: -2
08-20 22:40:33.917 3233-3233/? E/cutils-trace: Error opening trace file: Permission denied (13)
08-20 22:40:33.955 3233-3233/? E/memtrack: Couldn't load memtrack module (No such file or directory)
08-20 22:40:33.955 3233-3233/? E/android.os.Debug: failed to load memtrack module: -2
08-20 22:40:35.530 3245-3245/? E/cutils-trace: Error opening trace file: Permission denied (13)
08-20 22:40:35.539 3248-3248/? E/cutils-trace: Error opening trace file: Permission denied (13)
08-20 22:40:35.580 3248-3248/? E/memtrack: Couldn't load memtrack module (No such file or directory)
08-20 22:40:35.580 3248-3248/? E/android.os.Debug: failed to load memtrack module: -2
08-20 22:40:35.596 3245-3245/? E/memtrack: Couldn't load memtrack module (No such file or directory)
08-20 22:40:35.596 3245-3245/? E/android.os.Debug: failed to load memtrack module: -2
08-20 22:40:36.241 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 273, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
08-20 22:40:36.242 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
08-20 22:40:36.242 2300-2397/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
08-20 22:40:36.242 2300-2397/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
08-20 22:40:41.263 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 281, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
08-20 22:40:41.263 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
08-20 22:40:41.264 2300-2397/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
08-20 22:40:41.264 2300-2397/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
08-20 22:40:46.292 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 297, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
08-20 22:40:46.293 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
08-20 22:40:46.293 2300-2397/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
08-20 22:40:46.293 2300-2397/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
08-20 22:40:51.312 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 305, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
08-20 22:40:51.313 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
08-20 22:40:51.313 2300-2397/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
08-20 22:40:51.314 2300-2397/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
08-20 22:40:56.343 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 313, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
08-20 22:40:56.343 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
08-20 22:40:56.343 2300-2397/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
08-20 22:40:56.344 2300-2397/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
08-20 22:41:01.361 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 321, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
08-20 22:41:01.362 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
08-20 22:41:01.362 2300-2397/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
08-20 22:41:01.363 2300-2397/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
08-20 22:41:06.388 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 329, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
08-20 22:41:06.388 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
08-20 22:41:06.388 2300-2397/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
08-20 22:41:06.389 2300-2397/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
08-20 22:41:17.555 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 337, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
08-20 22:41:17.555 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
08-20 22:41:17.555 2300-2397/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
08-20 22:41:17.555 2300-2397/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
08-20 22:41:22.571 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 345, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
08-20 22:41:22.572 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
08-20 22:41:22.572 2300-2397/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
08-20 22:41:22.572 2300-2397/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
08-20 22:41:27.590 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 353, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
08-20 22:41:27.591 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
08-20 22:41:27.591 2300-2397/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
08-20 22:41:27.591 2300-2397/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
08-20 22:41:32.612 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 361, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
08-20 22:41:32.614 2300-2397/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
08-20 22:41:32.614 2300-2397/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
08-20 22:41:32.615 2300-2397/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded`

**Comment by JoaquimLey** [comment]
Yes it is working, If you read the stacktrace you can see the issue is related to:

`E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.`
