### ISSUE TITLE
You should never create an App object yourself

### ISSUE THREAD

**Issue by ech0s7r** [JoaquimLey/bus-eta#2]
https://github.com/JoaquimLey/bus-eta/blob/26ce1a7f4b2dff12c6efa2292531035e70bfc4ae/app/src/main/java/com/joaquimley/buseta/App.java#L22

**Comment by JoaquimLey** [comment]
This is the case where the app instance is null.

**Comment by ech0s7r** [comment]
Try to use the App object you instantiate... and you will see what happens!

**Comment by JoaquimLey** [comment]
Why are you being so aggressive @ech0s7r? Have you read the whole app class? Have you noticed that I'm binding the `sIntance` on the `onCreate()`?
https://github.com/JoaquimLey/bus-eta/blob/26ce1a7f4b2dff12c6efa2292531035e70bfc4ae/app/src/main/java/com/joaquimley/buseta/App.java#L17

So the case where the instance is null is a very edgy one but should be handled nonetheless. 

So don't be so condescending, but thanks for your input 💪.

**Comment by ech0s7r** [comment]
Please, as already suggested, test your App when sInstance is null and see what happens. The getApplicationContext() will return of course null. It's totally wrong to instantiate the application class object as you did. It doesn't make sense, only Android can instantiate the Application object for you.
Please read documentation about Application class.
